version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8082
    volumes:
      - ./client/src:/app/src  # For development hot reload
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app  # For development hot reload

networks:
  default:
    name: gridappsd-network